language: bash
sudo: required
services:
  - docker

env:
  - VERSION=1.0.0
  - VERSION=edge
matrix:
  exclude:
    - evn: VERSION=1.0.0 TRAVIS_EVENT_TYPE=cron
  allow_failures:
    - env: VERSION=edge

script:
  - ./build versions/$VERSION/options
  - ./build test versions/$VERSION/options

deploy:
  - provider: script
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && ./build push versions/$VERSION/options
    on:
      branch: master
